### ISSUE TITLE
Is there an update for AHK V2 planned?

### ISSUE THREAD

**Issue by qb-0** [Spawnova/ShinsImageScanClass#14]
I've noticed that you've updated your Overlay to V2. Is there a chance that you update that amazing scanning class as well?

**Comment by Spawnova** [comment]
Yes this will have a v2 option as well probably within 2 weeks from now

**Comment by Spawnova** [comment]
the class has been converted for use with ahk v2, let me know if you run into any issues as I do not use v2 and may have missed something
