### ISSUE TITLE
#NoEnv messes with Scanned Colors ?

### ISSUE THREAD

**Issue by KRN-8** [Spawnova/ShinsImageScanClass#17]
is it possible that #NoEnv at the start of the script would somehow mess with returned colors ?
or maybe the Overlay class does it, hmm dunno, its wierd. 

both GetPixel and PixelRegion return the most Random colors

all im doing is scanning for solid background color of the ads region and im getting the most RNG results, then if i scan the game region it works as expected XD

**Comment by KRN-8** [comment]
OMG thats Genious !
will try and let u know about the results ;-)

**Comment by KRN-8** [comment]
u wont beleive this !   XD
it is an android emulator btw

after app launched:
![PrntScn_appLaunched](https://github.com/Spawnova/ShinsImageScanClass/assets/67783847/b654dc87-f0c8-4fdc-8f40-e05acc338242)

after minimizing the window in windows:
![PrntScn_afterMinimize](https://github.com/Spawnova/ShinsImageScanClass/assets/67783847/e3fb271c-0a37-48fa-8e1a-65dd26268a2d)

what i see with Alt+PrtScrn:
![WindowPrintScreen](https://github.com/Spawnova/ShinsImageScanClass/assets/67783847/94235d93-dfb4-4870-82b0-1e065f456a88)

soo essentially the buffer keeps whatever the window had when it was different size (what doesnt fit is just not updated)
no way XD

**Comment by KRN-8** [comment]
soo when the app launches sideways, then turns upright which changes window size, the side pannel will have the sideways picture of the launching app. he ha he he :-)

**Comment by KRN-8** [comment]
LOL sometimes it screenshots it EXACTLY as windows screenshot does !!!   whaaaat ???
ok but i do NOT know how to reproduce THAT.

**Comment by KRN-8** [comment]
tried both EXE and Class and both behave the same way

imho. its not issue with incorrect hooking but with the buffer available/used by the class internals ;-)

**Comment by Spawnova** [comment]
It is a problem in which the application updates it's hdc, commonly there may be issues with directx/opengl applications such as bluestacks, I can only verify that in the case of bluestacks I've had success using the class but similar problems to you when not using it.
Unfortunately due to my capture method using gdi it's not as versatile as more modern approaches, but I'm not yet learned enough to implement those methods
