### ISSUE TITLE
Does not work with ahk_id

### ISSUE THREAD

**Issue by Wardenahk** [Spawnova/ShinsImageScanClass#23]
Hello, I noticed such a problem when using title everything works fine. Pixels and clicks happen in the background.
`scan := new ShinsImageScanClass("title")`

But if I use ahk_id, it stops working in the background.

`
id := 1705254
scan := new ShinsImageScanClass(%id%)
`
or
`
id := 1705254
scan := new ShinsImageScanClass(ahk_id %id%)
`

On ahk v2, ahk_id works perfectly.

**Comment by Spawnova** [comment]
hi, to use window id you need to prefix it with ahk_id as a string

```ahk
id := 1705254
scan := new ShinsImageScanClass("ahk_id " id)
```
