### ISSUE TITLE
I can't make it work with games

### ISSUE THREAD

**Issue by vonrar** [Spawnova/ShinsImageScanClass#26]
Unsuccessful Case test:

* Img to look for:
![Overwatch](https://github.com/Spawnova/ShinsImageScanClass/assets/81275484/f474d4ab-c711-42fd-8b9c-803830493fa4)

* Img saved with SaveImage:
![no_encontrado](https://github.com/Spawnova/ShinsImageScanClass/assets/81275484/e7781903-93b4-4838-999b-fb2fd5463889)

and doesn't find it, that's with overwatch 2, it happens the same with helldivers 2.

But, it works with discord:

successful Case test

* Img to look for:
![discord](https://github.com/Spawnova/ShinsImageScanClass/assets/81275484/898cf6e6-b36d-4bc5-9053-ed39c5750cb1)

* Img saved with SaveImage:
![encontrado](https://github.com/Spawnova/ShinsImageScanClass/assets/81275484/f757fc4b-e73b-4f00-9bb7-f6568b6289b2)

Both games run in windowed fullscreen

The code i'm using:

```
#SingleInstance force
#NoEnv ; Recommended for performance and compatibility with future AutoHotkey releases.
#Persistent ; Stay open in background
SendMode Input ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir% ; Ensures a consistent starting directory.
#include ShinsImageScanClass\ShinsImageScanClass.ahk
global imageScan := new ShinsImageScanClass()
ScanStratagems(){
        if (imageScan.Image("Overwatch.png")){
            imageScan.SaveImage("encontrado.png")
        } Else {
            imageScan.SaveImage("no_encontrado.png")
        }
    }
```

**Comment by Spawnova** [comment]
My class may not be compatible with all games, if however SaveImage returns a correct looking image it should work

In your case you are searching for identical match, meaning if even 1 pixel shifts color very slightly it will fail, you can try to increase variance for better results

```ahk
#SingleInstance force
#NoEnv ; Recommended for performance and compatibility with future AutoHotkey releases.
#Persistent ; Stay open in background
SendMode Input ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir% ; Ensures a consistent starting directory.
#include ShinsImageScanClass\ShinsImageScanClass.ahk
global imageScan := new ShinsImageScanClass()

exitapp


Test(){
	if (imageScan.Image("Overwatch.png",20,x,y)) { ;20 variance
		imageScan.SaveImage("encontrado.png")
		msgbox % "Image was found at " x "," y
	} Else {
		imageScan.SaveImage("no_encontrado.png")
		msgbox % "Image was not found"
	}
}
    ```
