### ISSUE TITLE
Unset Var warning when run

### ISSUE THREAD

**Issue by dovry** [Spawnova/ShinsImageScanClass#27]
![image](https://github.com/Spawnova/ShinsImageScanClass/assets/15201298/a0872079-d787-481e-bfba-26fe9df96d82)

V2 issue

this variable in the screenshot above -which is initialized later somewhere?- throws this error when included in a script

adding `#Warn VarUnset, Off` below the `#Requires ahk v2` line fixed it for me.

Thanks for the excellent class, btw.

**Comment by Spawnova** [comment]
Well that's embarrassing lol, I don't have this class loaded into vscode or I would have seen that, new update just a moment, thanks for pointing it out!
