### ISSUE TITLE
Specifying Window

### ISSUE THREAD

**Issue by tgdonovan** [Spawnova/ShinsImageScanClass#3]
If I specify a window, my code doesn't work.

This doesn't work
scan := new ShinsImageScanClass("ahk_exe notepad.exe")
t := scan.image("c:\tmp\notepad.png",0,X,Y)  ;this returns 0 and x and y are not defined

The following does work
scan := new ShinsImageScanClass()
t := scan.image("c:\tmp\notepad.png",0,X,Y) ;returns value and x and y are set

Am I don't something wrong. If I use saveimage, with the first section, it does save the expected image. I've tried with other programs and then decided to try with notepad to minimize possible other issues. The notepad.png is just a image of the icon on the caption bar.

**Comment by Spawnova** [comment]
Hey there!

When specifying a title it grabs the client area of the window, which generally does not include the title and menu bar
I can add an option that allows for grabbing the entire window but prior testing resulting in strange window sizes, I'll have that pushed out later today after I do some more testing

**Comment by Spawnova** [comment]
Okay I've added support for scanning the window space instead of client space

When creating the class instance you can now enter the second parameter as 0 to use window instead of client

```AutoHotkey
scan := new ShinsImageScanClass("ahk_exe notepad.exe",0)
```

Let me know if that fixes the issue!

**Comment by tgdonovan** [comment]
Thank you so much of making the explanation and making the change. Unfortunately still having same issue. Modified the code to include the ,0 after the wintitle. Without wintitle, shows the location, but still with wintitle, and the 0 doesn't (and the image is visible, while my hope is for the image to be able to be behind another window, haven't gotten there yet).

I wonder if the fact that I am running RDP to a remote machine is contributing to this. I do a scan.saveimage, with wintitle and the new 0 parameter and the image it saves is the window I expect so that part looks fine, but because of encoding and stuff I'm not sure if that is an exact test of what you are comparing to the image I am providing.

**Comment by tgdonovan** [comment]
With no expectations, but if I don't ask, you can't say yes, I will outline what I'd like to see added to your class. What intrigued me about your class is ability to check hidden window (I realize not minimized). I would like to be able check for text. I'd like to combine the OCR routines (such as used be in the-automators windowsnipping tool) with your tool. I keep looking to see if I could figure out how to add, but so far I haven't been able to figure out how I would tie your routines and the OCR routines together. If I added, I would create a Text function, like your image functions  Text(lookfor,returnx,returny). The OCR function needs a random access stream to the image. which I'm not quite sure (at least yet) on how to provide from your update function.

Anyway, food for thought. Great work.

**Comment by Spawnova** [comment]
I think I may know what the problem is based on your description... I will have an updated version out soon that should hopefully solve this issue

As far as OCR goes, I can look into providing an example that adapts that OCR script with my class, not sure if I will be able to but if possible I will do so =)

**Comment by Spawnova** [comment]
Okay I've pushed out the changes, **Hopefully** that works lol

**Comment by tgdonovan** [comment]
That worked, thank you. (Doing work around the house, so checking this is a nice break.

**Comment by Spawnova** [comment]
Awesome good to hear! Let me know if any other issues come up =)
